spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mos_burgers
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  spring:
    servlet:
      multipart:
        enabled: true
        max-file-size: 2MB
        max-request-size: 2MB
